<h3>Manutenção de Usuarios</h3>

<br style="clear:both;" />
<?php echo $this->msg?>
<br style="clear:both;" />

<table class="listagem" style="width: 800px;">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th>Login</th>
			<th>Status</th>
			<th>Profile</th>
			<th>Clientes</th>
			<th>Atualizar</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->list as $user){?>
		<tr>
			<td><?=$user->getId();?></td>
			<td><?=$user->getName();?></td>
			<td><?=$user->getLogin();?></td>
			<td><?=$this->Status($user->getStatus(), $user->getId());?></td>
			<td><?=$this->Profile($user->getRoleId(), $user->getId());?></td>
			<td><?=$this->Client($user->getClients("", $user->getId()), $user->getId());?></td>
			<td>
				<input class="btAzul" type="button" value="Atualizar" name="btAdmUser" onClick="admUserSave(<?=$user->getId();?>);">
			</td>
		</tr>
	<?php }?>
	</tbody>
</table>