<form name="frmSearchComp" id="frmSearchComp" method="post" action="<?php echo $this->baseUrl('/prime/component/search');?>">

	<label for="title" style="color: #003399; font-size: 13px; margin: 5px;">Título</label>
	<input type="text" name="title" id="title" maxlength="100" size="30" value="<?php echo $this->title;?>">
	
	<input type="submit" name="btSearchComp" class="btAzul" style='background: url("/image/top-bottom.gif") repeat-x scroll 50% 50% transparent; border: 0 none; color: #003399; height: 25px;' id="btSearchComp" value="Pesquisar">
</form>