<div id="pesquisa">
	<form name="frmSearch" action="#pesquisa" onSubmit="return pesqHist(this);">
		<label for="date_ini">Data Início:</label> 
		<input type="text" name="date_ini" id="date_ini" size="10">
		
		<label for="date_end">Data Fim:</label>
		<input type="text" name="date_end" id="date_end" size="10">
		
		<input type="submit" name="btpesq" value="Pesquisar" class="btAzul">
	</form>
</div>