<?php
/**Forçando download de arquivo (maneira simplista**/
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename='.basename($this->file));
    header('Content-Transfer-Encoding: binary');
	    header('Expires: 0');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Pragma: public');
    header('Content-Length: ' . filesize($this->file));
    ob_clean();
    flush();
    readfile($this->file);